@startuml ControleFluxoCAixaContainer
title Controle de Fluxo de Caixa

actor Comerciante as comerciante
boundary "Sistema de Controle de Fluxo de Caixa" as sistema
database "Banco de Dados" as banco

comerciante --> sistema: Realiza lançamentos (débitos e créditos)
sistema --> banco: Armazena lançamentos
sistema --> comerciante: Gera relatório de saldo diário consolidado

@enduml